data:
  db_path: "data/agri.db"
  test_size: 0.2
  random_state: 42

preprocessing:
  numerical:
    imputer: "median"  # Options: "mean", "median", "most_frequent"
    scaler: "standard"  # Options: "standard", "minmax", "none"

  categorical:
    encoder: "onehot"   # Options: "onehot", "label", "none"
    imputer: "most_frequent"  # Options: "most_frequent", "constant"

regression_models:
  RandomForestRegressor:
    n_estimators: 100
    random_state: 42
    max_depth: 10


regression_param_grid:
  model__n_estimators: [250, 450, 650, 700]
  model__max_depth: [null, 2, 4]

classification_models:
  RandomForestClassifier:
    n_estimators: 100
    random_state: 0
